[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Maid = "nightcycle/maid@2.0.0"
Signal = "nightcycle/signal@1.0.2"